# Generated by Django 3.2.9 on 2021-11-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrisDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter1', models.FloatField()),
                ('parameter2', models.FloatField()),
                ('parameter3', models.FloatField()),
                ('parameter4', models.FloatField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
